language: generic
sudo: required
services:
  - docker

  before_install:
    - docker build -t prasad2099/docker-react -f Dockerfile.dev .

  
  script:
    - docker run -e CI=true prasad2099/docker-react npm run test
